const routes = {
    LANDING: "/",
    HOME: "/home",
    EDIT_PROFILE: "/edit-profile",
    REGISTER: "/register",
    CLIENTS: "/clients",
    CASES: "/cases",
    SUPPORT: "/support",
    PERSONAL_DETAILS: "/personal-details",
    LEGAL_DOCUMENTS: "/legal-documents",
    ABOUT_US: "/about-us",
    CONSULTATION: "/consultation",
    CONSULTATION_DETAILS: "/consultation/:id",
    CASE_HISTORY: "/case-history",
    PAYMENT_HISTORY: "/payment-history",
    LEGAL_FEES: "/legal-fees",
    VIEW_ALL_CASES: "/cases/all",
    FAVORITE_CASES: "/cases/favorites",
    ADD_TESTIMONIAL: "/add-testimonial",
    SETTINGS: "/settings",
    PROMOTIONS: "/promotions",
    PRIVACY_POLICY: "/policy/privacy-policy",
    TERMS_OF_SERVICE: "/policy/terms-of-service",
    FAQS: "/faqs",
    LEGAL_RESOURCES: "/legal-resources",
    CONTACT_US: "/contact-us",
};
export default routes;
